name: labram-lora
channels:
  - pyg   
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch>=2.0
  - torchvision>=0.15
  - torchaudio>=2.0
  - pytorch-cuda=11.8
  - numpy=1.26.*
  - scipy=1.11.*
  - scikit-learn=1.3.*
  - tqdm>=4.65
  - jupyter
  - ipykernel
  - matplotlib
  - seaborn
  - pytorch-scatter 
  - pip

  - pip:
    - torcheeg
    - braindecode>=0.8.1
    - wandb
    - pyyaml
    - h5py
    - peft
