name: labram-lora-gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - h5py
  - pyyaml
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda
  - wandb
  - pip
  - pip:
      - torcheeg
      - peft
      - transformers
      - accelerate
      - safetensors
      - einops
      - torch-scatter
      - torch-sparse
      - torch-geometric